<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>12401939-b1e4-4fc8-ae26-9e5bd1a539c4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DinkToPdf" Version="1.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.23" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.23">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
    <PackageReference Include="QuestPDF" Version="2026.2.2" />
    <PackageReference Include="Rotativa.AspNetCore" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\Camilo Pineda\source\repos\SalaReuniones\SalaReuniones\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\Camilo Pineda\source\repos\SalaReuniones\SalaReuniones\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\Rotativa\" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\images\HaloLogoBlue.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
